# Generated by Django 4.2.3 on 2025-03-02 21:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0002_contactmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='text_choice',
            new_name='choice_text',
        ),
        migrations.AddField(
            model_name='choice',
            name='voters',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
